### ISSUE TITLE
Clone de proyectos generados no permite resolución de dependencias con bower

### ISSUE THREAD

**Issue by juusechec** [udistrital/generator-oas#1]
Al clonar un proyecto realizado con el generador, el comando **grunt serve** dice:
```
Warning: Error: angular is not installed. Try running `bower install`. Use --force to continue.
```
Pero al ejecutar un **bower install --save** se obtiene el error:
```
bower                                  ECONFLICT Unable to find suitable version for angular
```

**Comment by juusechec** [comment]
Se presenta con la versión actual de http://tuleap.udistrital.edu.co/plugins/git/academica/syllabus

**Comment by andresvia** [comment]
No creo que un proyecto clonado deba funcionar sin hacer cambios así que no sé si este sea realmente un bug, o no estamos usando yeoman bien. 🤔

**Comment by juusechec** [comment]
Realicé un proyecto con el generador, pero al intentar resolver las dependecias de este en otro computador no las resuelve, tal vez el generador está poniendo una versión que no se puede resolver en bower, eso es lo que hay que mirar.

**Comment by fabianLeon** [comment]
en teoria **bower install** deberia funcionar

**Comment by fabianLeon** [comment]
intenta con **npm install** dentro del app generado

**Comment by fabianLeon** [comment]
al estar bower y node_modules dentro del git ignore, entonces es necesario ejecutar **npm install** y **bower install** para resolver este proble,a
