### ISSUE TITLE
Mejorar el README.md generado para el proyecto.

### ISSUE THREAD

**Issue by juusechec** [udistrital/generator-oas#2]
No se muestra como se pueden suplir las dependencias por medio de npm o bower o si existe un script dispuesto para eso.

**Comment by fabianLeon** [comment]
El readme de github no es el mismo de npm.
https://www.npmjs.com/package/generator-oas
https://github.com/udistrital/generator-oas

**Comment by fabianLeon** [comment]
ya lo resolvi :)
