### ISSUE TITLE
La documentación de ejecución del script no está dentro de este mismo repositorio

### ISSUE THREAD

**Issue by juusechec** [udistrital/generator-oas#3]
La documentación de como ejecutar el generador está en tuleap http://tuleap.udistrital.edu.co/plugins/mediawiki/wiki/gestion/index.php/Generador_yeoman_personalizado_para_la_oficina_asesora_de_sistemas lo cuál no es conveniente ya que no está accesible para el público en general y debe ser parte de la entrega para este software libre.

**Comment by andresvia** [comment]
Esto está fácil así que creo que lo puedo hacer yo.

**Comment by juusechec** [comment]
Resuelto https://github.com/udistrital/generator-oas/pull/5
