### ISSUE TITLE
Bower instala dependencias mientras se pregunta la versión de AngularJS

### ISSUE THREAD

**Issue by juusechec** [udistrital/generator-oas#4]
El prompt del instalador espera por una respuesta sobre la versión de ángular mientras bower instala dependencias haciendo que la pregunta quede salida de contexto. Puede buscarse una mejora o la razón de por qué se hace.

**Comment by andresvia** [comment]
Creo que el generador no debería hacer preguntas, eso también simplificaría la documentación y dejaría los proyectos uniformes.

**Comment by juusechec** [comment]
Es buena idea, yo solo quería darle enter a todo y que me dijera success XD.

**Comment by fabianLeon** [comment]
la forma para que no pregunte la version de angular es mediante la siguiente configuración dentro de bower.json
se está añadiendo a generator-oas, hay que darle mantenimiento. hasta ahora habría que actualizar esta resolución manualmente cada vez que suba de version angular.  
"resolutions": {
    "angular": "1.6.3"
  },

**Comment by juusechec** [comment]
@fabianLeon si puedes porfa revisar https://github.com/udistrital/generator-oas/commit/a8ccfc0c76240946095cff1459c001f3db8ffe4f

**Comment by fabianLeon** [comment]
Gracias, @juusechec ya lo revise y funciona a la perfección.
podrias hacer un pullRequest a master?
