### ISSUE TITLE
Hacer que "grunt build" vuelva a funcionar

### ISSUE THREAD

**Issue by andresvia** [udistrital/generator-oas#8]
Hice un proyecto generator-angular puro, y después de ciertos tweaks con ayuda de esto: https://github.com/yeoman/generator-angular/issues/1320#issuecomment-247893884 pude hacer que:

    grunt build

Funcione, sin embargo en generator-oas, no funciona como se espera, es decir, no produce en `./dist/` la aplicación lista para ser publicada en un servidor web cualquiera (apache, s3, algún CDN, etc), es decir minify, uglyfly, cdnfy, los cambios que ocurren en los `require` de manera automática para que la aplicación funcione luego de esto, etc.

En algún lugar entre los cambios que le hicimos a generator-angular rompimos ese comportamiento el cuál necesitamos para llevar esta aplicación a cualquier ambiente que no sea desarrollo, es decir, diferente de "`grunt serve`"

**Comment by salcedogeiner** [comment]
El build no funciona debidamente ya que en la archivo \templates\common\app\index.html no se realiza la construcción de algunos elementos. Se recomienda incluir en la construcción de bower los scripts referenciados de manera similar:
```
<!-- build:js(.) scripts/extras.js -->
  <!-- bower:js -->
  <script src="scripts/services/token.js"></script>
  <script src="scripts/controllers/menu.js"></script>
  <script src="scripts/controllers/footer.js"></script>
  <!-- endbower -->
  <!-- endbuild -->
```

**Comment by fabianLeon** [comment]
se realizaron modificaciones para hacer que grunt build funcionara, adicional a lo que Geiner indicó, se tuvo que revisar font-awesome y angular-material. 

recomiendo realizar pruebas
